import { ltr } from "../bidi.ts";

/**
 * Parses the coordinate format in [`cities.json`](../stores/cities.json).
 *
 * **AI Disclosure**: This whole function was generated by an LLM and later
 * modified by a human.
 */
export function dmsStringToDecimal(dms: string) {
  const m =
    /^\s*([+-]?\d+(?:\.\d+)?)\s*°\s*([+-]?\d+(?:\.\d+)?)\s*'\s*([+-]?\d+(?:\.\d+)?)\s*"?\s*$/.exec(
      dms,
    );

  if (!m) return undefined;

  const deg = Number(m[1]);
  const min = Number(m[2]);
  const sec = Number(m[3]);

  const sign = deg < 0 ? -1 : 1;
  const absDeg = Math.abs(deg);

  return sign * (absDeg + min / 60 + sec / 3600);
}

export function formatCoordinate(lat: number, lng: number) {
  return ltr`${Math.abs(lat).toFixed(3)}°${lat < 0 ? "S" : "N"} ${Math.abs(lng).toFixed(3)}°${lng < 0 ? "W" : "E"}`;
}
