import * as v from "valibot";
import { dontCare, readonlyArray, readonlyObject } from "../schema.ts";

export const TtacDrugLicense = readonlyObject({
  id: v.number(),
  indexId: v.number(),
  indexEnName: v.string(),
  indexFaName: v.string(),
  licenseOwnerCompanyName: v.string(),
  licenseOwnerCompanyId: v.number(),
  drugGenericName: v.string(),
  drugGenericFaName: v.string(),
  drugGenericId: v.number(),
  drugGenericCode: dontCare(v.number()),
  drugFamilyFaTitle: dontCare(),
  drugFamilyEnTitle: dontCare(),
  enBrandName: v.string(),
  faBrandName: v.string(),
  brandOwnerCompanyName: v.string(),
  isBulk: v.boolean(),
  licenseCode: dontCare(),
  gtin: dontCare(),
  irc: v.string(),
  producerCompanyName: dontCare(),
  producerCompanyCountryName: dontCare(),
  drugLicenseItemPackageLayoutAttachmentIds: readonlyArray(v.string()),
  appearanceAttachmentsIds: dontCare(),
  unitOfUsePackaging: v.string(),
  isO2: dontCare(),
  countryFaName: dontCare(),
  persianExpirationDate: dontCare(),
  status: dontCare(),
  packageConsumerPrice: v.nullable(v.number()),
  nameDescription: dontCare(),
  producerCountryISO2: dontCare(v.string()),
  producerCountryEnName: dontCare(v.string()),
  producerCountryFaName: dontCare(v.string()),
});
export type TtacDrugLicense = v.InferOutput<typeof TtacDrugLicense>;
