import * as v from "valibot";
import { dontCare, readonlyArray, readonlyObject } from "../schema.ts";

export const TtacDrugLicense = readonlyObject({
  appearanceAttachmentsIds: dontCare(),
  brandOwnerCompanyName: dontCare(v.string()),
  countryFaName: dontCare(dontCare()),
  drugFamilyEnTitle: dontCare(dontCare()),
  drugFamilyFaTitle: dontCare(dontCare()),
  drugGenericCode: dontCare(v.number()),
  drugGenericFaName: dontCare(v.string()),
  drugGenericId: dontCare(v.number()),
  drugGenericName: dontCare(v.string()),
  drugLicenseItemPackageLayoutAttachmentIds: dontCare(
    readonlyArray(v.string()),
  ),
  enBrandName: dontCare(v.string()),
  faBrandName: v.string(),
  gtin: dontCare(),
  id: dontCare(v.number()),
  indexEnName: dontCare(v.string()),
  indexFaName: dontCare(v.string()),
  indexId: v.number(),
  irc: v.string(),
  isBulk: dontCare(v.boolean()),
  isO2: dontCare(),
  licenseCode: dontCare(),
  licenseOwnerCompanyId: dontCare(v.number()),
  licenseOwnerCompanyName: dontCare(v.string()),
  nameDescription: dontCare(),
  packageConsumerPrice: dontCare(v.nullable(v.number())),
  persianExpirationDate: dontCare(),
  producerCompanyCountryName: dontCare(),
  producerCompanyName: dontCare(),
  producerCountryEnName: dontCare(v.string()),
  producerCountryFaName: dontCare(v.string()),
  producerCountryISO2: dontCare(v.string()),
  status: dontCare(),
  unitOfUsePackaging: dontCare(v.string()),
});
export type TtacDrugLicense = v.InferOutput<typeof TtacDrugLicense>;
